name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build all 🔧
        run: yarn build

      - name: Deploy documentation 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/docs/build

      - name: Linting
        run: yarn --cwd packages/react-vvm lint

      - name: Running unit tests
        run: yarn --cwd packages/react-vvm jest --coverage

      - name: Setting upsteam
        run: git push --set-upstream origin master

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: packages/react-vvm/coverage/coverage-summary.json
          branches: master,preprod,staging

      - name: Generating the size badge
        run: |
          node .github/scripts/size-badge.js
          git add badges/weight.svg
          git commit -m "Generating the size badge"
          git push
